config/routes.rb
Rails.application.routes.draw do
  #get 'inicio/index'
  resources :main
  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create]
    resources :sessions, only: [:new, :create]
  end
  get 'logout', to: 'authentication/sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "inicio#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, uniqueness: true,
    format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
      message: :invalid
    }

    validates :dni, presence: true, uniqueness: true,
    format: {
      with: /\A[0-9]+\z/,
      message: :invalid
    }

    validates :password, presence: true
    validates :nombre, presence: true,
    format: {
      with: /\A[a-z-A-Z]+\z/,
      message: :invalid
    }
    validates :apellido, presence: true,
    format: {
      with: /\A[a-z-A-Z]+\z/,
      message: :invalid
    }

    before_save :downcase_attributes

    private
    
    def downcase_attributes
        self.email = email.downcase
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    helper_method :user_authenticated?

    
    def user_authenticated?
        !current_user.nil?
    end

    def current_user
        User.find session[:user_id] if session[:user_id]
    end

    before_action :set_current_user
    before_action :protect_pages

    private

    def set_current_user
        Current.user = User.find_by(id: session[:user_id]) 
    end

    def protect_pages
        redirect_to "/" unless Current.user
    end
end

app/controllers/authentication/sessions_controller.rb
class Authentication::SessionsController < ApplicationController
    skip_before_action :protect_pages

    def new
    end

    def create
        @user = User.find_by("dni = :dni", { dni: params[:dni] })
        if @user&.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to "/main/index"
        else
            redirect_to new_session_path
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to new_session_path
    end

end

app/controllers/authentication/users_controller.rb
class Authentication::UsersController < ApplicationController
    skip_before_action :protect_pages
    
    def new
        @user= User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            session[:user_id] = @user.id
            redirect_to "/main/index"
        else
            render :new, status: :unprocessable_entity
        end
    end

    private
    
    def user_params
        params.require(:user).permit(:email, :dni, :nombre, :apellido, :password)
    end
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  skip_before_action :protect_pages

  def index
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        
    end
    def show
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/authentication/users/new.html.erb
<%= form_with(model: @user) do |form| %>
  <% @user.errors.full_messages.each do |error| %>
    <div>
      <%= error %>
    </div>
  <% end %>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :dni %>
    <%= form.number_field :dni %>
  </div>

    <div>
        <%= form.label :nombre %>
        <%= form.text_field :nombre %>
    </div>

    <div>
        <%= form.label :apellido %>
        <%= form.text_field :apellido %>
    </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inicio/index.html.erb
<h1>Inicio</h1> 


<% if user_authenticated? %>
  <div class="row">
    <div class="col">
      <%= link_to 'Logout', logout_path %>
    </div>
  </div>

  
<% else %>
  <div class="row">
    <div class="col">
    <div>
      <%= link_to 'Registrarse', new_user_path %>
      <%= link_to 'Iniciar Sesion', new_session_path %>
    </div>
  </div>
  <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oh My Dog - Veterinaria</title>
    <meta name="viewport" content="widht=device-widht,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>




    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  
  
  </head>
    

  <body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/main/index">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Oh My Dog</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="/">
                    <i class="fa fa-home" aria-hidden="true"></i>
                    <span>Inicio</span></a>
            </li>

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="index.html">
                    <i class="fa fa-book" aria-hidden="true"></i>
                    <span>Turnos</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle" ></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                             <% if user_authenticated? %>
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.nombre%></span>
                             <% else %>
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">inicia sesion</span>
                             <%end%>
                          </a>
                          <ul class="dropdown-menu">
                            <% if user_authenticated? %>
                              <li><a class="dropdown-item" href="#">Mi perfil</a></li>
                              <li><a class="dropdown-item" href="#"><%= link_to 'Logout', logout_path %></a></li>
                            <%else%>
                              <li><a class="dropdown-item" href="#"><%= link_to 'Iniciar Sesion', new_session_path %></a></li>
                            <%end%>
                          </ul>
                        </li>
                </nav>
                <!-- End of Topbar -->
               
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <%= yield %>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
     
</body>

</html>

app/views/main/index.html.erb
<h1>Bienvenido!</h1>

app/views/main/show.html.erb
<h1>Bienvenido!</h1>

app/views/shared/_header.html.erb
<h1>OhMyDog</h1>